(in-package #:git-agent-workflow/tests)

(defun run-tests ()
  (git-agent-workflow/tests.git:run-tests)
  (git-agent-workflow/tests.refs:run-tests)
  (git-agent-workflow/tests.config:run-tests)
  (git-agent-workflow/tests.workspace:run-tests)
  (git-agent-workflow/tests.state:run-tests)
  (git-agent-workflow/tests.deploy:run-tests)
  (git-agent-workflow/tests.commit:run-tests)
  (git-agent-workflow/tests.show:run-tests)
  (git-agent-workflow/tests.check:run-tests)
  (git-agent-workflow/tests.help:run-tests)
  (git-agent-workflow/tests.hook:run-tests)
  (git-agent-workflow/tests.cli:run-tests)
  t)
